name: devops
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v2

      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1

      - name: Install JS dependencies
        # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: make install

      - name: Run e2e tests
        run: make ci-e2e-test

      - name: elm-analyse
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: elm-analyse
